import React, { useState, useEffect } from 'react';
import { FileText, BarChart3, TrendingUp, Download, Calendar, PieChart, Loader2 } from 'lucide-react';
import { supabase } from '../supabaseClient';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import 'jspdf-autotable';

const ReportsAnalytics = () => {
  const [selectedPeriod, setSelectedPeriod] = useState('month');
  const [employees, setEmployees] = useState([]);
  const [loading, setLoading] = useState(true);
  const [deptStats, setDeptStats] = useState([]);

  // --- 1. FETCH DATA DARI SUPABASE ---
  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      const { data, error } = await supabase
        .from('employees')
        .select('*');
      
      if (error) throw error;
      setEmployees(data || []);
      calculateStats(data || []);
    } catch (error) {
      console.error('Error fetching data:', error.message);
    } finally {
      setLoading(false);
    }
  };

  // --- 2. HITUNG STATISTIK REAL ---
  const calculateStats = (data) => {
    // Hitung jumlah per departemen
    const counts = {};
    data.forEach(emp => {
      const dept = emp.departemen || 'Unassigned';
      counts[dept] = (counts[dept] || 0) + 1;
    });

    const total = data.length;
    
    // Format data untuk grafik
    const stats = Object.keys(counts).map(dept => ({
      name: dept,
      employees: counts[dept],
      percentage: total === 0 ? 0 : Math.round((counts[dept] / total) * 100),
      color: getRandomColor(dept) // Warna dinamis
    })).sort((a, b) => b.employees - a.employees); // Urutkan dari terbanyak

    setDeptStats(stats);
  };

  const getRandomColor = (key) => {
    const colors = ['bg-blue-500', 'bg-green-500', 'bg-purple-500', 'bg-orange-500', 'bg-pink-500', 'bg-indigo-500'];
    let hash = 0;
    for (let i = 0; i < key.length; i++) hash = key.charCodeAt(i) + ((hash << 5) - hash);
    return colors[Math.abs(hash) % colors.length];
  };

  // --- 3. GENERATE PDF REPORT ---
  const generatePDF = (reportTitle) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(18);
    doc.text(`HR Pro - ${reportTitle}`, 14, 20);
    doc.setFontSize(11);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 30);
    doc.text(`Total Karyawan: ${employees.length}`, 14, 36);

    // Tabel Statistik Departemen
    const tableColumn = ["Departemen", "Jumlah Karyawan", "Persentase"];
    const tableRows = deptStats.map(dept => [dept.name, dept.employees, `${dept.percentage}%`]);

    doc.autoTable({
      startY: 45,
      head: [tableColumn],
      body: tableRows,
    });

    // Footer simple
    doc.text("Generated by HR Pro SaaS System", 14, doc.lastAutoTable.finalY + 20);
    
    doc.save(`${reportTitle.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
  };

  // --- 4. GENERATE EXCEL REPORT ---
  const generateExcel = () => {
    // Sheet 1: Data Karyawan Lengkap
    const empData = employees.map(e => ({
      Nama: e.nama,
      Departemen: e.departemen,
      Posisi: e.posisi,
      Status: e.status
    }));
    const ws1 = XLSX.utils.json_to_sheet(empData);

    // Sheet 2: Statistik
    const statsData = deptStats.map(d => ({
      Departemen: d.name,
      Jumlah: d.employees,
      Persentase: d.percentage + '%'
    }));
    const ws2 = XLSX.utils.json_to_sheet(statsData);

    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws1, "Detail Karyawan");
    XLSX.utils.book_append_sheet(wb, ws2, "Statistik");

    XLSX.writeFile(wb, `HR_Report_Full_${Date.now()}.xlsx`);
  };

  // --- MOCK KPI DATA (Karena belum ada tabel KPI di DB) ---
  const kpiData = [
    { name: 'Turnover Rate', value: 5.2, target: 10, trend: 'down', unit: '%', color: 'red' }, // Mock
    { name: 'Active Employees', value: employees.filter(e => e.status === 'Aktif').length, target: employees.length, trend: 'up', unit: '', color: 'green' }, // Real
    { name: 'Departments', value: deptStats.length, target: 5, trend: 'up', unit: '', color: 'blue' }, // Real
  ];

  if (loading) return <div className="p-8 flex justify-center"><Loader2 className="animate-spin text-indigo-600" /></div>;

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <div className="mb-6 flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-gray-800 mb-2">Laporan & Analytics</h1>
          <p className="text-gray-600">Data real-time berdasarkan database karyawan Anda.</p>
        </div>
        <div className="flex gap-2">
           <button onClick={generateExcel} className="bg-green-600 hover:bg-green-700 text-white px-4 py-2 rounded-lg flex items-center gap-2 text-sm font-medium transition-colors">
             <Download size={16}/> Export Excel
           </button>
        </div>
      </div>

      {/* Period Selector (Visual Only for MVP) */}
      <div className="bg-white rounded-lg shadow p-4 mb-6">
        <div className="flex items-center gap-4">
          <Calendar className="w-5 h-5 text-gray-600" />
          <span className="font-medium text-gray-700">Periode Data:</span>
          <div className="flex gap-2">
            {['month', 'quarter', 'year'].map((period) => (
              <button
                key={period}
                onClick={() => setSelectedPeriod(period)}
                className={`px-4 py-2 rounded-lg font-medium transition-colors ${
                  selectedPeriod === period
                    ? 'bg-indigo-500 text-white'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                }`}
              >
                {period === 'month' ? 'Bulan Ini' : period === 'quarter' ? 'Kuartal' : 'Tahun'}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Report Types Cards */}
      <div className="grid md:grid-cols-3 gap-6 mb-8">
        {[
          { title: 'Laporan Karyawan', icon: FileText, color: 'bg-blue-100 text-blue-600', desc: 'Daftar lengkap karyawan & status.' },
          { title: 'Analisis Departemen', icon: BarChart3, color: 'bg-green-100 text-green-600', desc: 'Distribusi beban kerja per divisi.' },
          { title: 'Performa Tahunan', icon: TrendingUp, color: 'bg-purple-100 text-purple-600', desc: 'Ringkasan pertumbuhan tahunan.' }
        ].map((report, idx) => (
          <div key={idx} className="bg-white rounded-lg shadow-lg p-6 hover:shadow-xl transition-shadow">
            <div className={`w-12 h-12 rounded-lg flex items-center justify-center mb-4 ${report.color}`}>
              <report.icon className="w-6 h-6" />
            </div>
            <h3 className="font-bold text-lg mb-2 text-gray-800">{report.title}</h3>
            <p className="text-sm text-gray-600 mb-4">{report.desc}</p>
            <button
              onClick={() => generatePDF(report.title)}
              className="w-full bg-gray-50 hover:bg-indigo-50 text-indigo-600 border border-indigo-100 py-2 rounded-lg font-semibold transition-colors flex items-center justify-center gap-2"
            >
              <Download className="w-4 h-4" /> Download PDF
            </button>
          </div>
        ))}
      </div>

      {/* Real-time Department Stats */}
      <div className="grid md:grid-cols-3 gap-6">
        {/* Kolom Kiri: Distribusi Departemen */}
        <div className="md:col-span-2 bg-white rounded-lg shadow-lg p-6">
          <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
            <PieChart className="w-6 h-6 text-indigo-600" /> Distribusi Departemen (Real-time)
          </h2>

          <div className="space-y-5">
            {deptStats.length === 0 ? (
              <p className="text-gray-500 text-center py-8">Belum ada data karyawan.</p>
            ) : (
              deptStats.map((dept, idx) => (
                <div key={idx}>
                  <div className="flex justify-between mb-1">
                    <span className="text-sm font-medium text-gray-700">{dept.name}</span>
                    <span className="text-sm font-medium text-gray-500">{dept.employees} org ({dept.percentage}%)</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2.5">
                    <div className={`${dept.color} h-2.5 rounded-full transition-all duration-1000`} style={{ width: `${dept.percentage}%` }}></div>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Kolom Kanan: KPI Summary */}
        <div className="bg-white rounded-lg shadow-lg p-6">
          <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
            <TrendingUp className="w-6 h-6 text-indigo-600" /> Key Metrics
          </h2>
          <div className="space-y-6">
            {kpiData.map((kpi, idx) => (
              <div key={idx} className="border-b border-gray-100 pb-4 last:border-0 last:pb-0">
                <div className="flex justify-between items-center mb-1">
                  <span className="text-gray-600 text-sm">{kpi.name}</span>
                  <span className={`text-xs px-2 py-0.5 rounded ${kpi.trend === 'up' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
                    {kpi.trend === 'up' ? '▲' : '▼'} Trend
                  </span>
                </div>
                <div className="flex items-end gap-2">
                  <span className="text-2xl font-bold text-gray-800">{kpi.value}{kpi.unit}</span>
                  <span className="text-xs text-gray-400 mb-1">/ Target {kpi.target}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ReportsAnalytics;